language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  global:
      - PYTHONPATH=.
      -SECRET_KEY=relapse92
# command to run tests
script: 
  - "python Tests.py test"


  